[package]
name = "shellcode-injector"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
winapi = { version = "0.3.9", features = ["winbase", 
"processthreadsapi", "handleapi", "memoryapi", 
"errhandlingapi", "winnt", "memoryapi"] }